#!/bin/sh -ex

make() {
  /usr/bin/make "-j$(nproc)" "$@"
}

cmake() {
  /usr/bin/cmake -DCMAKE_CXX_FLAGS="$CXXFLAGS " -DCMAKE_C_FLAGS="$CFLAGS " "$@"
}

# Let's be nice
renice -n 19 -p $$

for dep in /build/deps/*
do
  echo making "$dep"
  cd /build/lib
  . "$dep"
done

cd /
rm -rf /build/lib/* /build/deps/*
