#!/usr/bin/env python3

import sys
from subprocess import run

# Remove attached "-lgcc_s" flag.
def rm_gccs(arg):
  return arg != '-lgcc_s'

def main(argv):
  args = ['/usr/bin/clang'] + list(filter(rm_gccs, argv))
  error = run(args)
  sys.exit(error.returncode)

main(sys.argv[1:])
