#!/bin/sh

set -ex

cd /build/src

wget -q https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
tar xjf ffmpeg-snapshot.tar.bz2

cd ffmpeg

./configure \
  --prefix="/usr" \
  --pkg-config-flags="--static" \
  --extra-cflags="-static -Wl,-Bdynamic,-lgcc_s,-Bstatic" \
  --extra-ldflags="-static" \
  --extra-libs="-lpthread -lm" \
  --bindir="/build/bin" \
  --enable-static \
  --enable-gpl \
  --enable-gnutls \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree && \
make -j4 && \
make install && \
hash -r
