# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ exp/github-ci ]

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        gcc: [10]
        build_arch:
          - "x86-64"
          - "broadwell"
          - "silvermont"
          - "znver2"

    steps:
      - uses: actions/checkout@v2

      - name: Build and Publish latest Docker image
        uses: VaultVulp/gp-docker-action@1.1.8
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          image-name: "gcc-${{ matrix.gcc }}-${{ matrix.build_arch }}"
          build-context: builder
          dockerfile: "builder/Dockerfile.gcc-${{ matrix.gcc }}"
          custom-args: "--build-arg BUILD_ARCH=${{ matrix.build_arch }}"
